version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-install
      context: ./angular4
    image: alexsimons/nodeinstall
    volumes:
      - ./web-content:/app

#runs the node install