version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-install
      context: ./web-content
    image: alexsimons/nodeinstall:9.2.0
    volumes:
      - ./web-content:/app

#runs the node install